on:
  [push]

name: cowsay-my-name

jobs:
  cow:
    name: Cowsays
    runs-on: ubuntu-latest
    steps:
    - name: Ship it
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'Junior Lima'
        color: 'red'
